USE LAB1

CREATE TABLE PR_CUSTOMERS(
ID INT  IDENTITY(1,1) PRIMARY KEY,
PASSWORDS CHAR(10),
EMAIL VARCHAR(30),
NAME VARCHAR(20)
)

CREATE TABLE PR_ADMIN (
ADMIN_ID INT IDENTITY(1,1) PRIMARY KEY,
USERNAME VARCHAR(20),
PASSWORDS CHAR(10)
)


CREATE TABLE PR_DELIVERYMEN (
ID INT IDENTITY(1,1) PRIMARY KEY ,
ADMIN_ID INT FOREIGN KEY REFERENCES PR_ADMIN(ADMIN_ID),
NAME VARCHAR(20),
PASSWORDS CHAR(10),
EMAIL VARCHAR(30)  
)

CREATE TABLE PR_ORDER1(
 ORDER_ID INT IDENTITY(1,1) PRIMARY KEY,
 ID INT FOREIGN KEY REFERENCES PR_DELIVERYMEN(ID),
 PRICE INT,
 STATUSES VARCHAR(30) NULL,
 QUANTITY INT ,
CUTOMER_ID INT FOREIGN KEY REFERENCES PR_CUSTOMERS(ID) NOT NULL,
ORDER_DATE DATE
 )

 CREATE TABLE PR_PAYMENTS (
 PAYMENT_ID INT IDENTITY(1,1) PRIMARY KEY ,
 PAYMENT_TYPE VARCHAR(20) ,
 ID INT FOREIGN KEY REFERENCES PR_CUSTOMERS(ID),
ORDER_ID INT FOREIGN KEY REFERENCES PR_ORDER1(ORDER_ID),
PRICE INT
) 

CREATE TABLE PR_FOOD_ITEMS1(
FOOD_ID INT IDENTITY(1,1) PRIMARY KEY ,
ADMIN_ID INT FOREIGN KEY REFERENCES PR_ADMIN(ADMIN_ID),
 FOOD_NAME VARCHAR(20) NOT NULL,
 PRICES INT )  


 CREATE TABLE PR_DELIVERYMEN_COMPOSITE (
ID INT FOREIGN KEY REFERENCES PR_DELIVERYMEN(ID),
CITY VARCHAR(20) NOT NULL,
AREA VARCHAR(50) NOT NULL,
PRIMARY KEY(ID,CITY,AREA)
)


CREATE TABLE PR_DELIVERYMEN_MULTIVALUES (
 ID INT FOREIGN KEY REFERENCES PR_DELIVERYMEN(ID),
   PHONE_NO VARCHAR(11) NOT NULL,
   PRIMARY KEY (ID,PHONE_NO) )

CREATE TABLE PR_ORDERS_COMPOSITE (
ID INT FOREIGN KEY REFERENCES PR_ORDER1(ORDER_ID),
CITY VARCHAR(20) NOT NULL,
AREA VARCHAR(50) NOT NULL,
PRIMARY KEY(ID,CITY,AREA)
)

CREATE TABLE PR_ORDERS_MULTIVALUES
( ORDER_ID INT FOREIGN KEY REFERENCES PR_ORDER1(ORDER_ID),
   PHONE_NO VARCHAR(11) NOT NULL,
   PRIMARY KEY (ORDER_ID,PHONE_NO) )
  
 
 CREATE TABLE ORDER_FOOD1 (
 ORDER_ID INT FOREIGN KEY REFERENCES PR_ORDER1(ORDER_ID),
 FOOD_ID INT FOREIGN KEY REFERENCES PR_FOOD_ITEMS1(FOOD_ID),
 QUANTITY INT 
 )
   
	 USE LAB1
	 SELECT * FROM PR_FOOD_ITEMS1
	SELECT * FROM PR_ORDER1
	SELECT * FROM ORDER_FOOD1
	SELECT * FROM PR_DELIVERYMEN
	SELECT * FROM PR_PAYMENTS
	SELECT * FROM PR_DELIVERYMEN_COMPOSITE
	SELECT * FROM PR_DELIVERYMEN_MULTIVALUES
	SELECT * FROM PR_ORDERS_COMPOSITE
	SELECT * FROM PR_ORDERS_MULTIVALUES
	SELECT * FROM PR_CUSTOMERS
	SELECT * FROM PR_ADMIN
